### ISSUE TITLE
Support for foreach/problems with value option?

### ISSUE THREAD

**Issue by marcelgruber** [MakerStudios/ko-calendar#8]
Hi there,

I'm having problems running this within a foreach loop. When I leave the "value" as the default ko,observable(), the error message is "You cannot apply bindings multiple times to the same element."

There also seems to be an issue with the "value" option of opts. When I input "self.some_observable()", I get an error message saying "value must be an observable", even though it is an observable.

Thoughts are appreciated!

**Comment by jakiestfu** [comment]
Instead `self.some_observable()` is not an observable because it is a function that returns a primitive value. What you'd want to pass is the observable itself as `self.some_observable` (without parenthesis).
