### ISSUE TITLE
ko.calendar.version throws undefined

### ISSUE THREAD

**Issue by ready4god2513** [MakerStudios/ko-calendar#9]
Minifying the file appends ```footer: "ko.calendar.version = \"" + pkg.version + "\";"``` to the minified file via grunt.  That is fine, except it is outside of the module loader and thus ```ko``` can be undefined when the file is first requested.   I am more than happy to make any changes and submit a PR, but I was wanting to know if there was a reason that ```ko.calendar.version``` needed to be callable rather than just inside of a comment.

**Comment by jakiestfu** [comment]
We could probably just ditch that footer option since this is a small library anyways. Not sure how much use it serves.

**Comment by ready4god2513** [comment]
Sounds great to me.  I just changed it to ```footer: "/*! ko.calendar.version = \"" + pkg.version + "\"; */"``` for my local copy, but if it can be removed, then that is great.  Want a PR for that?

**Comment by jakiestfu** [comment]
Sure, if you wouldn't mind! Since this impacts code, could you up the version in package.json and run the build tasks too?

**Comment by ready4god2513** [comment]
@jakiestfu #10
